inputs_def:
  - handle: video_source
    description: Input
    json_schema:
      type: string
      ui:widget: file
    value: ""
outputs_def:
  - handle: ffmpeg_source
    description: Output
    json_schema:
      contentMediaType: oomol/var
  - handle: file_address
    json_schema:
      type: string
icon: ":fa6-solid:file-import:currentColor:"
ui:
  default_width: 350
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
